name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]


jobs:
  build:
    name: Test for Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10' ]
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4.3.1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Oncoexporter
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .[test]

    - name: Run unit and integration tests
      run: |
        pytest
